name: 'setup services jenkins container and install jenkins-cli.jar'
description: 'Setup services jenkins container and install jenkins-cli.jar.'
author: 'srz_zumix'
inputs:
  service_id:
    description: "jenkins service container id"
    required: true
  port:
    description: "jenkins service container port"
    default: '8080'
    required: false
  plugins_file:
    description: "install plugin list file"
    default: ''
    required: false
  install_suggested_plugins:
    description: "install suggested plugins"
    default: false
    required: false
runs:
  using: "composite"
  steps:
    - name: Wait Launch Jenkins
      shell: bash
      run: |
        "${GITHUB_ACTION_PATH}/wait-launch.sh" "${{ inputs.service_id }}"
    - name: Setup CLI
      shell: bash
      env: 
        JENKINS_URL: http://localhost:${{ inputs.port }}
      run: |
        "${GITHUB_ACTION_PATH}/setup-cli.sh"
    - name: Install Jenkins Suggested Plugins
      shell: bash
      run: |
        "${GITHUB_ACTION_PATH}/install-plugins.sh" "${GITHUB_ACTION_PATH}/resources/DefaultJenkinsPlugins.txt"
      if: "inputs.install_suggested_plugins == 'true'"
    - name: Install Jenkins Plugins
      shell: bash
      run: |
        "${GITHUB_ACTION_PATH}/install-plugins.sh" "${{ inputs.plugins_file }}"
      if: "inputs.plugins_file != ''"

branding:
  icon: 'settings'
  color: 'yellow'
