name: 'setup services jenkins container'
description: 'Setup services jenkins container.'
author: 'srz_zumix'
inputs:
  service_id:
    description: "jenkins service container id"
    required: true
  port:
    description: "jenkins service container port"
    default: '8080'
    required: false
  pulgins_file:
    description: "install plugin list file"
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Wait Launch Jenkins
      run: |
        until docker logs "${{ inputs.service_id }}" 2>&1 | grep "Jenkins is fully up and running"; do
          sleep 30; echo "waiting..."
        done
        docker logs "${{ inputs.service_id }}"
    - name: Download CLI
      working-directory: ${{ runner.temp }}
      run: |
        curl -sSOL "http://localhost:${{ inputs.port }}/jnlpJars/jenkins-cli.jar"
    - name: Install Jenkins Plugins
      run: |
        xargs -I{} java -jar "${{ runner.temp }}/jenkins-cli.jar" -s "http://localhost:${{ inputs.port }}" install-plugin {} < ${{ inputs.pulgins_file }}
      if: "${{ inputs.pulgins_file }} != ''"
    - name: Get session-id
      id: session-id
      working-directory: ${{ runner.temp }}
      run: |
        echo "##[set-output name=before;]$(java -jar jenkins-cli.jar -s "http://localhost:${{ inputs.port }}" session-id)"          
    - name: Restart Jenkins
      working-directory: ${{ runner.temp }}
      run: |
        java -jar jenkins-cli.jar -s "http://localhost:${{ inputs.port }}" restart
    - name: Wait restart
      working-directory: ${{ runner.temp }}
      run: |
        until java -jar jenkins-cli.jar -s "http://localhost:${{ inputs.port }}" session-id; do
          sleep 30; echo "waiting..."
        done
        while java -jar jenkins-cli.jar -s "http://localhost:${{ inputs.port }}" session-id | grep "${{ steps.session-id.outputs.before }}"; do
          sleep 30; echo "waiting..."
        done

branding:
  icon: 'settings'
  color: 'yellow'
