name: 'Setup Jenkins Post Check'
description: 'Setup Jenkins Post Check Commands'

inputs:
  id:
    required: true

runs:
  using: "composite"
  steps:
    - name: $github
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "${GITHUB_CONTEXT}"
    - name: $job
      shell: bash
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: |
        echo "${JOB_CONTEXT}"
    - name: $runner
      shell: bash
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
        echo "${RUNNER_CONTEXT}"
    - name: ENV
      shell: bash
      run: |
        env
    - name: ENV (GITHUB_)
      shell: bash
      run: |
        env | grep GITHUB_ | sort
    - name: Inputs
      shell: bash
      env:
        INPUTS_CONTEXT: ${{ toJson(inputs) }}
      run: |
        echo "${INPUTS_CONTEXT}"
    - name: jenkins log
      shell: bash
      run: |
        echo '::group::jenkins log'
        jenkins-log
        echo '::endgroup::'
    - name: list-plugins
      shell: bash
      run: |
        echo '::group::jenkins-cli list-plugins'
        jenkins-cli list-plugins
        echo '::endgroup::'
    - name: print system message
      shell: bash
      run: |
        jenkins-cli-groovyfile testdata/printSystemMessage.groovy arg1 arg2
