name: 'Setup Jenkins Post Check'
description: 'Setup Jenkins Post Check Commands'

runs:
  using: "composite"
  steps:
    - name: list-plugins
      shell: bash
      run: |
        echo '::group::jenkins-cli list-plugins'
        jenkins-cli list-plugins
        echo '::endgroup::'
    - name: print system message
      shell: bash
      run: |
        jenkins-cli-groovy println "jenkins.model.Jenkins.get().getSystemMessage()"
