name: 'setup-service-jenkins-post-action'
description: 'setup-service-jenkins post action workaround.'
author: 'srz_zumix'

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'

branding:
  icon: 'settings'
  color: 'yellow'
