name: Example
on:
  push:

jobs:
  setup-jenkins-example:
    runs-on: ubuntu-latest
    services:
      jenkins:
        image: jenkins/jenkins:lts-jdk11
        # image: jenkins/jenkins:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          # disable setup wizard
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
          - 8080:8080
          - 50000:50000
      agent1:
        image: jenkins/jnlp-agent-jdk11
    steps:
    - uses: srz-zumix/setup-service-jenkins@feature/fix_example
      with:
        name: jenkins
        nodes: |
          agent1
          agent2
        plugins: |
          job-dsl
          workflow-job
    - name: List online nodes
      run: |
        jenkins-cli-groovy 'jenkins.model.Jenkins.get().computers.findAll{ it.isOnline() }.each { println it.displayName }'
